### ISSUE TITLE
 missing E2E protection

### ISSUE THREAD

**Issue by dayangshanbaoye** [chrizog/someipy#23]
Are you planning to implement end-to-end protection?
For example, the common protection scheme AUTOSAR E2E Profile 4.

**Comment by chrizog** [comment]
Hello @dayangshanbaoye , thanks for your interest in the library. Currently, it is not planned to be implemented. However, if you need it urgently, you can contact me via email or linkedin and we can discuss a solution.

**Comment by dayangshanbaoye** [comment]
ok, thanks all the same. I shall try to implement by myself, if possible I'll ask for you professional advice through email. I have an idea on how to protect the message with profile4 already, and I shall try to implement the message counter as the session handler .
